[package]
name = "amstrad_cpc"
version = "0.1.0"
edition = "2024"

[dependencies]
zilog_z80 = { path = "../ZilogZ80" }
sdl2 = { version = "0.38.0", features = ["ttf"] }
toml = "1.1.4"
serde = { version = "1.0.229", features = ["derive"] }
directories = "6.0.0"
image = { version = "0.25", default-features = false, features = ["png"] }
